"""
Small hand-curated seed of unmistakably famous man-made objects that the
automated Wikipedia list-harvests either miss entirely (modern engineering
landmarks postdate/are excluded from UNESCO; individual crown jewels are
buried in prose, not list rows) or under-represent by region (Middle East,
Southeast Asia, Oceania, Africa, South America). Each entry still resolves
to a real en.wikipedia.org article via the same canonicalization pass as
every other source -- this is a supplementary seed, not a bypass.
"""

SEED = [
    # --- Ancient & New 7 Wonders not already covered elsewhere ---
    ("Hanging Gardens of Babylon", "monument", "Middle East", "ancient"),
    ("Statue of Zeus at Olympia", "sculpture", "Europe", "classical"),
    ("Temple of Artemis", "building", "Middle East", "classical"),
    ("Mausoleum at Halicarnassus", "monument", "Middle East", "classical"),
    ("Colossus of Rhodes", "sculpture", "Europe", "classical"),
    ("Lighthouse of Alexandria", "monument", "Africa", "classical"),
    ("Petra", "site", "Middle East", "classical"),
    ("Chichen Itza", "site", "North America", "medieval"),

    # --- Named crown jewels / regalia not caught by list pages ---
    ("St Edward's Crown", "artefact", "Europe", "early-modern"),
    ("Imperial State Crown", "artefact", "Europe", "modern"),
    ("Sovereign's Sceptre with Cross", "artefact", "Europe", "early-modern"),
    ("Sovereign's Orb", "artefact", "Europe", "early-modern"),
    ("Coronation Spoon", "artefact", "Europe", "medieval"),
    ("Koh-i-Noor", "artefact", "South Asia", "medieval"),
    ("Cullinan Diamond", "artefact", "Africa", "modern"),
    ("Imperial Crown of Iran", "artefact", "Middle East", "modern"),
    ("Iranian Crown Jewels", "artefact", "Middle East", None),
    ("Peacock Throne", "artefact", "South Asia", "early-modern"),
    ("Spanish Crown Jewels", "artefact", "Europe", None),
    ("Imperial Regalia of Japan", "artefact", "East Asia", "ancient"),
    ("Crown of Napoleon", "artefact", "Europe", "modern"),

    # --- Iconic manuscripts/documents outside the "illuminated" filter ---
    ("Domesday Book", "manuscript", "Europe", "medieval"),
    ("Magna Carta", "manuscript", "Europe", "medieval"),
    ("Gutenberg Bible", "manuscript", "Europe", "medieval"),
    ("Dead Sea Scrolls", "manuscript", "Middle East", "ancient"),
    ("Codex Sinaiticus", "manuscript", "Middle East", "ancient"),
    ("Voynich Manuscript", "manuscript", "Europe", "medieval"),
    ("Diamond Sutra", "manuscript", "East Asia", "medieval"),
    ("United States Declaration of Independence", "manuscript",
     "North America", "early-modern"),
    ("United States Constitution", "manuscript", "North America",
     "early-modern"),
    ("Rosetta Stone", "artefact", "Africa", "classical"),

    # --- Famous individual archaeological/portable artefacts ---
    ("Antikythera mechanism", "artefact", "Europe", "classical"),
    ("Sutton Hoo helmet", "artefact", "Europe", "medieval"),
    ("Bayeux Tapestry", "artefact", "Europe", "medieval"),
    ("Shroud of Turin", "artefact", "Europe", "medieval"),
    ("Ötzi", "artefact", "Europe", "ancient"),
    ("Venus of Willendorf", "sculpture", "Europe", "ancient"),
    ("Mask of Tutankhamun", "artefact", "Africa", "ancient"),
    ("Bust of Nefertiti", "sculpture", "Africa", "ancient"),
    ("Elgin Marbles", "sculpture", "Europe", "classical"),
    ("Terracotta Army", "sculpture", "East Asia", "ancient"),
    ("Nebra sky disc", "artefact", "Europe", "ancient"),
    ("Standard of Ur", "artefact", "Middle East", "ancient"),
    ("Great Star of Africa", "artefact", "Africa", "modern"),
    ("Fabergé egg", "artefact", "Europe", "modern"),
    ("Ardagh Chalice", "artefact", "Europe", "medieval"),
    ("Tara Brooch", "artefact", "Europe", "medieval"),
    ("Gundestrup cauldron", "artefact", "Europe", "ancient"),
    ("Amber Room", "artefact", "Europe", "early-modern"),
    ("Lewis chessmen", "artefact", "Europe", "medieval"),
    ("Portland Vase", "artefact", "Europe", "classical"),
    ("Warren Cup", "artefact", "Europe", "classical"),
    ("Vasa (ship)", "artefact", "Europe", "early-modern"),
    ("Mary Rose", "artefact", "Europe", "early-modern"),
    ("RMS Titanic", "artefact", "Europe", "modern"),
    ("Cutty Sark", "artefact", "Europe", "modern"),
    ("HMS Victory", "artefact", "Europe", "early-modern"),
    ("USS Arizona Memorial", "monument", "North America", "modern"),
    ("Liberty Bell", "artefact", "North America", "early-modern"),
    ("Spirit of St. Louis", "artefact", "North America", "modern"),
    ("Apollo 11 command module Columbia", "artefact", "North America",
     "modern"),

    # --- Modern engineering / architectural landmarks (post-date or
    #     are excluded from UNESCO/vital coverage) ---
    ("Golden Gate Bridge", "monument", "North America", "modern"),
    ("Brooklyn Bridge", "monument", "North America", "modern"),
    ("Tower Bridge", "monument", "Europe", "modern"),
    ("Sydney Harbour Bridge", "monument", "Oceania", "modern"),
    ("CN Tower", "building", "North America", "modern"),
    ("Space Needle", "building", "North America", "modern"),
    ("Petronas Towers", "building", "Southeast Asia", "modern"),
    ("Burj Al Arab", "building", "Middle East", "modern"),
    ("One World Trade Center", "building", "North America", "modern"),
    ("The Shard", "building", "Europe", "modern"),
    ("Chrysler Building", "building", "North America", "modern"),
    ("Willis Tower", "building", "North America", "modern"),
    ("Gateway Arch", "monument", "North America", "modern"),
    ("Hollywood Sign", "monument", "North America", "modern"),
    ("Big Ben", "building", "Europe", "modern"),
    ("London Eye", "monument", "Europe", "modern"),
    ("Buckingham Palace", "building", "Europe", "early-modern"),
    ("White House", "building", "North America", "modern"),
    ("Neuschwanstein Castle", "building", "Europe", "modern"),
    ("Potala Palace", "building", "East Asia", "early-modern"),
    ("Great Buddha of Kamakura", "sculpture", "East Asia", "medieval"),
    ("Leshan Giant Buddha", "sculpture", "East Asia", "medieval"),
    ("Himeji Castle", "building", "East Asia", "medieval"),
    ("Fushimi Inari-taisha", "building", "East Asia", "ancient"),
    ("Meenakshi Amman Temple", "building", "South Asia", "medieval"),
    ("Wat Arun", "building", "Southeast Asia", "early-modern"),
    ("Wat Phra Kaew", "building", "Southeast Asia", "early-modern"),
    ("Shwedagon Pagoda", "building", "Southeast Asia", "ancient"),
    ("Prambanan", "building", "Southeast Asia", "medieval"),
    ("One Pillar Pagoda", "building", "Southeast Asia", "medieval"),
    ("Marina Bay Sands", "building", "Southeast Asia", "modern"),
    ("Christ the Redeemer (statue)", "sculpture", "South America", "modern"),
    ("Cristo de la Concordia", "sculpture", "South America", "modern"),
    ("Nazca Lines", "monument", "South America", "ancient"),
    ("Moai", "sculpture", "South America", "medieval"),
    ("Teotihuacan", "site", "North America", "ancient"),
    ("Great Zimbabwe", "site", "Africa", "medieval"),
    ("Lalibela", "building", "Africa", "medieval"),
    ("Aksum obelisks", "monument", "Africa", "ancient"),
    ("Djinguereber Mosque", "building", "Africa", "medieval"),
    ("Great Mosque of Djenné", "building", "Africa", "modern"),
    ("Sheikh Zayed Grand Mosque", "building", "Middle East", "modern"),
    ("Dome of the Rock", "building", "Middle East", "medieval"),
    ("Western Wall", "monument", "Middle East", "ancient"),
    ("Church of the Holy Sepulchre", "building", "Middle East", "medieval"),
    ("Ishtar Gate", "monument", "Middle East", "ancient"),
    ("Behistun Inscription", "monument", "Middle East", "ancient"),
    ("Cyrus Cylinder", "artefact", "Middle East", "ancient"),
    ("Code of Hammurabi", "artefact", "Middle East", "ancient"),
    ("Great Sphinx of Giza", "sculpture", "Africa", "ancient"),
    ("Abu Simbel temples", "building", "Africa", "ancient"),
    ("Karnak", "site", "Africa", "ancient"),
    ("Valley of the Kings", "site", "Africa", "ancient"),
    ("Luxor Temple", "building", "Africa", "ancient"),

    # --- Continuing famous statues/monuments ---
    ("Motherland Calls", "sculpture", "Europe", "modern"),
    ("The Motherland Monument", "sculpture", "Europe", "modern"),
    ("Little Mermaid (statue)", "sculpture", "Europe", "modern"),
    ("Manneken Pis", "sculpture", "Europe", "early-modern"),
    ("Atomium", "building", "Europe", "modern"),
    ("Angel of the North", "sculpture", "Europe", "modern"),
    ("Christ of the Abyss", "sculpture", "Europe", "modern"),
    ("Charging Bull", "sculpture", "North America", "modern"),
    ("Mount Rushmore", "sculpture", "North America", "modern"),
    ("Crazy Horse Memorial", "sculpture", "North America", "modern"),
    ("Lincoln Memorial", "monument", "North America", "modern"),
    ("Washington Monument", "monument", "North America", "modern"),
    ("Jefferson Memorial", "monument", "North America", "modern"),
    ("Vietnam Veterans Memorial", "monument", "North America", "modern"),
    ("Arc de Triomphe", "monument", "Europe", "modern"),
    ("Brandenburg Gate", "monument", "Europe", "early-modern"),
    ("Berlin Wall", "monument", "Europe", "modern"),
    ("Cologne Cathedral", "building", "Europe", "medieval"),
    ("St Basil's Cathedral", "building", "Europe", "early-modern"),
    ("Chartres Cathedral", "building", "Europe", "medieval"),
    ("Milan Cathedral", "building", "Europe", "medieval"),
    ("Blue Mosque", "building", "Middle East", "early-modern"),
    ("Topkapi Palace", "building", "Middle East", "early-modern"),
    ("Alhambra", "building", "Europe", "medieval"),
]
