"""Curated history-themed answers used to seed grids and boost fill priority."""

HISTORY_WORDS = [
    # Ancient world
    "CAESAR", "AUGUSTUS", "NERO", "CALIGULA", "TRAJAN", "HADRIAN", "AURELIUS",
    "CONSTANTINE", "DIOCLETIAN", "RUBICON", "SENATE", "CONSUL", "LEGION",
    "CENTURION", "GLADIATOR", "AQUEDUCT", "FORUM", "COLOSSEUM", "PANTHEON",
    "POMPEII", "VESUVIUS", "CARTHAGE", "HANNIBAL", "SCIPIO", "ETRUSCAN",
    "REPUBLIC", "EMPIRE", "TOGA", "TRIBUNE", "ACTIUM", "ANTONY", "CLEOPATRA",
    "SPARTA", "ATHENS", "AGORA", "ACROPOLIS", "PARTHENON", "PERICLES",
    "SOCRATES", "PLATO", "ARISTOTLE", "HERODOTUS", "MARATHON", "SALAMIS",
    "LEONIDAS", "XERXES", "DARIUS", "CYRUS", "PERSIA", "ALEXANDER", "MACEDON",
    "PTOLEMY", "SPHINX", "PYRAMID", "PHARAOH", "NILE", "ROSETTA", "OBELISK",
    "NEFERTITI", "RAMESSES", "BABYLON", "HAMMURABI", "ASSYRIA", "SUMER",
    "ZIGGURAT", "PHOENICIA", "BYZANTIUM", "ATTILA", "GOTHS", "VANDALS",
    "FRANKS", "SAXONS", "HUNS", "GAUL", "DRUID", "CELTS",
    # Medieval
    "CHARLEMAGNE", "VIKINGS", "NORSEMEN", "RUNES", "HASTINGS", "NORMANS",
    "DOMESDAY", "CRUSADE", "SALADIN", "TEMPLAR", "MAGNACARTA", "AGINCOURT",
    "CRECY", "JOUST", "FEUDAL", "VASSAL", "SERF", "GUILD", "PLAGUE",
    "BYZANTINE", "OTTOMAN", "SULEIMAN", "JANISSARY", "MONGOLS", "KHAN",
    "SILKROAD", "MARCOPOLO", "SAMURAI", "SHOGUN", "KATANA", "DYNASTY",
    "MING", "TANG", "SONG", "HAN", "QING", "EDO", "KYOTO", "AZTEC", "INCA",
    "MAYA", "TENOCHTITLAN", "QUETZAL", "CASTLE", "MOAT", "SIEGE", "ABBEY",
    "MONK", "FRIAR", "POPE", "AVIGNON", "HERESY", "RELIC", "TITHE",
    # Early modern
    "RENAISSANCE", "REFORMATION", "LUTHER", "CALVIN", "HUGUENOT", "MEDICI",
    "BORGIA", "MACHIAVELLI", "GUTENBERG", "ERASMUS", "TUDOR", "ARMADA",
    "DRAKE", "RALEIGH", "MAYFLOWER", "JAMESTOWN", "COLUMBUS", "MAGELLAN",
    "CORTES", "PIZARRO", "CONQUISTADOR", "GALLEON", "PIRACY", "VERSAILLES",
    "RICHELIEU", "CROMWELL", "ROUNDHEAD", "RESTORATION", "BAROQUE",
    "ENLIGHTENMENT", "VOLTAIRE", "ROUSSEAU", "PETER", "TSAR", "ROMANOV",
    # Revolutions and the long 19th century
    "BASTILLE", "JACOBIN", "ROBESPIERRE", "DANTON", "MARAT", "GUILLOTINE",
    "NAPOLEON", "AUSTERLITZ", "BORODINO", "TRAFALGAR", "WATERLOO", "ELBA",
    "NELSON", "WELLINGTON", "METTERNICH", "GARIBALDI", "CAVOUR", "BISMARCK",
    "PRUSSIA", "HAPSBURG", "CRIMEA", "RAGTIME", "SUFFRAGE", "PANKHURST",
    "ABOLITION", "TUBMAN", "DOUGLASS", "LINCOLN", "GETTYSBURG", "APPOMATTOX",
    "YORKTOWN", "REVERE", "LIBERTY", "COLONY", "FRONTIER", "GOLDRUSH",
    "EMPRESS", "RAJ", "SEPOY", "ZULU", "BOER", "MEIJI", "OPIUM",
    # Twentieth century
    "SARAJEVO", "SOMME", "VERDUN", "YPRES", "ARMISTICE", "TRENCH", "UBOAT",
    "ZEPPELIN", "WEIMAR", "LENIN", "TROTSKY", "STALIN", "BOLSHEVIK", "SOVIET",
    "GULAG", "FASCISM", "BLITZ", "DUNKIRK", "ENIGMA", "NORMANDY", "DDAY",
    "YALTA", "CHURCHILL", "ROOSEVELT", "EISENHOWER", "MONTGOMERY", "ROMMEL",
    "NUREMBERG", "MARSHALL", "AIRLIFT", "NATO", "COLDWAR", "SPUTNIK",
    "GAGARIN", "APOLLO", "CUBA", "VIETNAM", "DETENTE", "GLASNOST",
    "PERESTROIKA", "BERLINWALL", "MANDELA", "APARTHEID", "GANDHI", "NEHRU",
    "PARTITION", "SUEZ", "KENNEDY", "CAMELOT", "WATERGATE", "HANOI",
    # General history vocabulary (easy fill)
    "ERA", "EPOCH", "EON", "AGE", "ANNALS", "ARCHIVE", "RELIC", "RUIN",
    "THRONE", "CROWN", "SCEPTER", "REGENT", "REIGN", "REALM", "DUKE", "EARL",
    "BARON", "KNIGHT", "SQUIRE", "HERALD", "BANNER", "TREATY", "EDICT",
    "DECREE", "CHARTER", "SCROLL", "SCRIBE", "PAPYRUS", "AMPHORA", "CHARIOT",
    "GALLEY", "TRIREME", "PHALANX", "CATAPULT", "RAMPART", "CITADEL",
    "BASTION", "ARMOR", "LANCE", "SABER", "MUSKET", "CANNON", "REDCOAT",
    "GENERAL", "ADMIRAL", "MARSHAL", "EXILE", "REGICIDE", "DYNAST", "HEIR",
    "LINEAGE", "MYTH", "SAGA", "EPIC", "ORACLE", "TEMPLE", "SHRINE", "IDOL",
    "ALTAR", "TOMB", "CRYPT", "MUMMY", "SARCOPHAGUS", "BARROW", "DOLMEN",
    # Peoples, places, myth & legend (clueable as history/legend)
    "ROMAN", "ROMANS", "GREEK", "GREEKS", "EGYPT", "CRETE", "DELPHI",
    "DELHI", "PETRA", "DOGE", "DOGES", "NUBIA", "PICTS", "MOORS", "SAXON",
    "TSARS", "TROY", "ILIAD", "HOMER", "AESOP", "MIDAS", "SOLON", "ZEUS",
    "HERA", "ARES", "EROS", "ODIN", "THOR", "LOKI", "OSIRIS", "ANUBIS",
    "ATHENA", "APOLLO", "TITAN", "TITANS", "ORACLE", "PARIS", "ROME",
    "ATHENA", "VATICAN", "KREMLIN", "ALAMO", "LOUVRE", "NOTREDAME",
]

# Deduplicate while preserving order
seen = set()
HISTORY_WORDS = [w for w in HISTORY_WORDS if not (w in seen or seen.add(w))]
